#!/usr/bin/zsh

# Check if no arguments
if [ -z $1 ]; then
  echo "No arguments were given... exiting..."
  exit 1
fi

nameProject=$(echo "$1" | sed 's/\ /-/g')
nameFile="$nameProject.cpp"
dirProject="/home/$USER/Projects/c++/$nameProject"
dirStart=$(pwd)
fileBegin=14

# Create dir for 
if [ ! -d $dirProject ]; then
  mkdir $dirProject
else
  echo "Directory already exists... exiting..."
  exit 1
fi

# Change direcotry and create file
cd $dirProject
touch $nameFile

# Create title for project
figlet $nameProject | sed 's/^/\/\/ /g' >> $nameFile
echo "//" >> $nameFile
echo "// Created by: Leevi Laitala" >> $nameFile
echo "// Date: $(date +'%Y/%m/%d %H:%M')" >> $nameFile
echo -e "\n\n\n"

cat "/home/$USER/Documents/templates/empty-cpp-file.cpp" >> $nameFile

vim "$dirProject/$nameFile" +$fileBegin
